version: '3.6'

services:
  erddap:
    container_name: ${COMPOSE_PROJECT_NAME}
    image: axiom/docker-erddap:latest
    environment:
        - TOMCAT_USER_ID=${TOMCAT_USER_ID}
        - TOMCAT_GROUP_ID=${TOMCAT_GROUP_ID}
        - VIRTUAL_HOST=${VIRTUAL_HOST}
        - VIRTUAL_PORT=${VIRTUAL_PORT:-8080}
        - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
        - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
        - type: tmpfs
          target: /tmp
        - type: tmpfs
          target: /usr/local/tomcat/temp
        - type: volume
          source: webapps
          target: /usr/local/tomcat/webapps
        - type: volume
          source: catalina
          target: /usr/local/tomcat/conf/Catalina/localhost
        - type: bind
          source: ./server.xml
          target: /usr/local/tomcat/conf/server.xml
        - type: bind
          source: ./logs
          target: /usr/local/tomcat/logs
        - type: bind
          source: ./erddapConfig
          target: /usr/local/tomcat/content/erddap 
        - type: bind
          source: ./erddapData
          target: /erddapData
        - type: bind
          source: /data
          target: /import
          
volumes:
  catalina:
    name: ${COMPOSE_PROJECT_NAME}_tomcat_catalina
    driver: local
  webapps:
    name: ${COMPOSE_PROJECT_NAME}_tomcat_webapps
    driver: local
    
networks:
  default:
    external:
      name: ${NETWORK:-clarity}